config:
    pattern:    /
    controller: main:check

install:
    pattern:    /configTiitz/install
    controller: main:check

endingInstall:
    pattern:	/configTiitz/endingInstall
    controller:	main:endInstallation


#entityGeneratorPOST:
#    pattern:    /configTiitz/entityGenerator
#    defaults:   {_controller: generator:posted}
#    requirements:
#    	_method: POST

entityGenerator:
    pattern:    /configTiitz/entityGenerator
    controller: generator:generateEntity

entityResumeInfo:
	pattern:	/configTiitz/entityGenerator
	controller: generator:entitiesResum