views:			/app/components/tzViews.class.php
router:			/app/components/tzRouter.class.php
sqlConnect:		/app/components/tzSQLConnect.class.php
errorCore:		/app/components/error/tzErrorCore.class.php
errorExtend:	/app/components/error/tzErrorExtend.class.php
devToobar: 		/app/components/devToolbar/tzToolbar.class.php
TiiTz: 			/app/components/tiitz.class.php
tzController: 	/app/components/tzController.class.php
validator:		/app/components/tzValidator.class.php
